[workspace]
members = ["super-sabicom-macro"]

[package]
name = "super-sabicom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
super-sabicom-macro = { path = "super-sabicom-macro", version = "0.1" }
log = "0.4.17"
modular-bitfield = "0.11.2"
thiserror = "1.0.31"

[dev-dependencies]
anyhow = "1.0.58"
argopt = "0.3.0"
compress-tools = "0.12.3"
env_logger = "0.9.0"
